"""ハードウェアバックエンドの Protocol（インターフェース）定義。"""

from typing import Protocol, runtime_checkable


@runtime_checkable
class DisplayBackend(Protocol):
    """ディスプレイバックエンドのインターフェース。"""

    show_response_during_tts: bool

    @property
    def is_sleeping(self) -> bool: ...
    def sleep(self) -> None: ...
    def wake(self) -> None: ...
    def cleanup(self) -> None: ...
    def set_backlight(self, level: int) -> None: ...
    def set_led(self, r: int, g: int, b: int) -> None: ...
    def stop_character(self) -> None: ...
    def start_character(self, state: str, tts=None) -> None: ...
    def set_character_state(self, state: str) -> None: ...
    def set_status(
        self,
        text: str,
        *,
        color: tuple[int, int, int] | None = None,
        subtitle: str | None = None,
        accent_color: tuple[int, int, int] | None = None,
    ) -> None: ...
    def append_response(self, delta: str) -> None: ...
    def set_response_text(self, text: str) -> None: ...
    def flush_response(self) -> None: ...
    def start_spinner(self, text: str = "") -> None: ...
    def stop_spinner(self) -> None: ...
    def set_session_name(self, name: str) -> None: ...
